# Config file for jet classification

#------------------------------------------------------------------
# These following parameters are used only in ML analysis
#------------------------------------------------------------------

# How many events to load for training
n_events: 500000

# How many events to sample
n_events_sample: 100

NUM_FEAT:   3
NUM_JET:    5
NUM_COND:   1

BATCH:      512
LR:         0.001
MAXEPOCH:   20
EARLYSTOP:  4
EMBED:      64
MAX_STEPS:  512   # The number of sampling steps
NORM:       'mean'
MJJMAX:     5000
MJJMIN:     2300
MODEL_NAME: 'FPCD_LHCO'


