# Config file for jet classification

#------------------------------------------------------------------
# These following parameters are used only in ML analysis
#------------------------------------------------------------------

# How many events to load for training
n_events: 50000

# How many events to sample
n_events_sample: 1000

NUM_FEAT:   3
NUM_JET:    5
NUM_COND:   1

BATCH:      128
LR:         0.0003
MAXEPOCH:   5
EARLYSTOP:  20
EMBED:      64
MAX_STEPS:  512   # The number of sampling steps
NORM:       'mean'
MJJMAX:     5000
MJJMIN:     2300
MODEL_NAME: 'FPCD_LHCO'


